#!/usr/bin/env python2.4

"""
$Id$
$URL$

Copyright (C) 2004 Matteo Merli <matteo.merli@gmail.com>
"""


VERSION = '0.0.1'

import sys, os

from lib import parser
from lib.template import DocumentTemplate

from optparse import OptionParser

opt = OptionParser(usage="usage: %prog [options] fo_file")

opt.add_option("-o", "--pdf", dest="pdfname",
		help="write PDF output to FILE", metavar="FILE")

opt.add_option('-v', '--version', action='store_true', dest='version', 
			help="show program's version number and exit")
		
opt.add_option('--verbose', action='store_true', dest='verbose', 
			help="be verbose...")

(options, args) = opt.parse_args()

if options.version:
	print "Pixies Formatting Objects - Pdf creator \nVersion %s" % VERSION
	print "Copyright (C) 2004 Matteo Merli <matteo.merli@gmail.com>"
	sys.exit(0)

if  len(args) != 1:
	opt.error('you should provide only one argument.')
	
foname = args[0]
if not options.pdfname:
	# We derive the PDF name from the input filename
	n = os.path.basename( '.'.join( foname.split('.')[:-1] ) + '.pdf' )
	options.pdfname = os.path.join( os.path.curdir, n )

dh = parser.go( foname )

doc = DocumentTemplate( options.pdfname , dh )
doc.build()


